services:

  api:
    container_name: api
    build: .
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.api.loadbalancer.server.port=8000

      - traefik.http.routers.api-http.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.api-http.entrypoints=http

      - traefik.http.routers.api-https.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.api-https.entrypoints=https
      - traefik.http.routers.api-https.tls=true
      - traefik.http.routers.api-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.api-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true
