services:

  backend:
    container_name: backend
    build: .
    restart: always
    networks:
      - traefik-public
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.backend.loadbalancer.server.port=8000

      - traefik.http.routers.backend-http.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.backend-http.entrypoints=http

      - traefik.http.routers.backend-https.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.routers.backend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.backend-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true
