services:

  api:
    container_name: api
    build: .
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      - traefik.http.services.api.loadbalancer.server.port=8000

      - traefik.http.routers.api.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls.certresolver=le
