services:

  api:
    container_name: api
    build: .
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      - traefik.http.services.api.loadbalancer.server.port=8000

      - traefik.http.routers.api.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.api.entrypoints=http

networks:
  traefik-public:
    external: true
