name: CI

on: [push, pull_request]

jobs:

  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: actions/setup-uv@v5
        with:
          version: "0.6.14"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
